In [2]:
from train_data.prepare_train_data import PrepareTrainData

In [3]:
from tensorflow import keras
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

model = keras.models.load_model('./one_dim/models/00045_generator')
noise = tf.random.normal(shape=(100, 1))
b = model.predict(noise)
plt.scatter(b[:, 0], np.zeros(b.shape[0]))
plt.xlim([-4, 4])
plt.show()

OSError: SavedModel file does not exist at: ./one_dim/models/00045_generator/{saved_model.pbtxt|saved_model.pb}

In [28]:
ptd = PrepareTrainData(buffer_size=10, batch_size=5)
data = ptd.dataset
print(len(list(data)))
print(type(data))

12000
<class 'tensorflow.python.data.ops.dataset_ops.BatchDataset'>


In [32]:
c = data.shuffle(buffer_size=5).batch(10)
len(c)

1200

In [12]:
a = data.take(5).batch(3)
a

<BatchDataset shapes: ((None, None, 28, 28, 1), (None, None, 10)), types: (tf.float32, tf.float32)>

In [29]:
b = next(iter(data))
len(list(b))

2

In [34]:
distr = PrepareTrainData(dataset_name='one_dim', buffer_size=10).dataset
distr

<BatchDataset shapes: (None, 1), types: tf.float32>

In [44]:
gfg = tf.data.Dataset.from_tensor_slices([[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]]])

for ele in gfg.batch(1):
    print(ele.numpy())
print('****')
for ele in gfg.batch(2):
    print(ele.numpy())
print('****')
for ele in gfg.batch(3):
    print(ele.numpy())


[[[1 1]
  [2 2]
  [3 3]]]
[[[4 4]
  [5 5]
  [6 6]]]
****
[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
****
[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [53]:
simple = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5]).shuffle(buffer_size=50)
for e in simple:
    print(e.numpy())

5
1
3
4
2


In [108]:
buffer_size = 10000
number_of_elements = 500
batch_size = 2

(x_train, y_train), (_, _) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(x_train.shape[0], 28, 28, 1).astype('float32')
x_train = (x_train - 127.5) / 127.5
# x_train = x_train / 255.0

y_train = tf.keras.utils.to_categorical(y_train)

dataset = tf.data.Dataset \
    .from_tensor_slices((x_train, y_train)) \
    .shuffle(buffer_size) \
    .batch(batch_size)
# print(len(dataset))
# print(dataset)
# dataset2 = dataset.map(lambda x, y: (x[0:100:2,:,:,:], y[0:100:2,:]))
# print(len(dataset2))
m = dataset.take(1)
for e1, e2 in m:
    print(e2)

tf.Tensor(
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(2, 10), dtype=float32)


In [94]:
arr = np.array([[1, 2, 3, 4, 5], [10, 11, 12, 13, 14]])

print(arr[:,1:4])
print("-------")
print(arr[:,::2])
print("-------")


[[ 2  3  4]
 [11 12 13]]
-------
[[ 1  3  5]
 [10 12 14]]
-------
[[1 2 3 4 5]]
-------
[[1 2 3 4 5]]
-------


In [110]:
-(tf.ones((2, 1)))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-1.],
       [-1.]], dtype=float32)>

In [111]:
a = tf.Variable([1, 2, 3, 4, 5])
tf.clip_by_value(a, 2, 4)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 2, 3, 4, 4], dtype=int32)>